# Generated by Django 4.1.2 on 2022-10-19 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiar',
            new_name='Familiares',
        ),
    ]
